version: '2'

volumes:
  nextcloud-app:
  nextcloud-custom-apps:
  nextcloud-config:
  nextcloud-data:
  nextcloud-pgsql:

services:
  nextcloud-app:
    image: nextcloud:12-fpm
    links:
      - nextcloud-db
    volumes:
      - nextcloud-app:/var/www/html
      - nextcloud-custom-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
    restart: always

  nextcloud-db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - nextcloud-pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SUPER_STRONG_PASSWORD # TODO: change me
      - POSTGRES_USER=nc

  nginx-front:
    image: alpine:3.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
    restart: always
    command: |
      sh -c "apk add --update nginx ; mkdir -pv /run/nginx && ln -svf /dev/stdout /var/log/nginx/access.log && ln -svf /dev/stderr /var/log/nginx/error.log && exec nginx "
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx-conf.d:/etc/nginx/conf.d:ro"
      - nextcloud-app:/var/www/html:ro
    links:
      - nextcloud-app
